namespace Imei
{
    public class DVDetail: DetailEntity
    {
        public string ma_dv { get; set; }
        public string ten_dv { get; set; }
        public bool vt_ton_kho { get; set; }
        public int km_yn { get; set; } 
        public string ma_sp { get; set; }
        public string ma_bp { get; set; }
        public string so_lsx { get; set; }
        public string dvt { get; set; }
        public decimal he_so { get; set; }
        public string ma_kho { get; set; }
        public string ma_vi_tri { get; set; }
        public string ma_lo { get; set; }
        public string ma_vv { get; set; }
        public string tk_vt { get; set; }
        public decimal so_luong { get; set; }
        public decimal gia_nt { get; set; }
        public decimal gia { get; set; }
        public decimal gia_nt2 { get; set; }
        public decimal gia2 { get; set; }
        public decimal tien_nt { get; set; }
        public decimal tien { get; set; }
        public decimal thue { get; set; }
        public decimal thue_nt { get; set; }
        public decimal tt { get; set; }
        public decimal tt_nt { get; set; }
        public string xstatus { get; set; }
        public decimal tien2 { get; set; }
        public decimal tien_nt2 { get; set; }
        public decimal cp_bh { get; set; }
        public decimal cp_bh_nt { get; set; }
        public decimal cp_vc { get; set; }
        public decimal cp_vc_nt { get; set; }
        public decimal cp_khac { get; set; }
        public decimal cp_khac_nt { get; set; }
        public decimal cp_nt { get; set; }
        public string stt_rec_ct { get; set; }
        public string stt_rec0ct { get; set; }
        public decimal gia_ban0 { get; set; }
        public decimal gia_ban_nt0 { get; set; }
        public decimal gia_ban { get; set; }
        public decimal gia_ban_nt { get; set; }
        public decimal tl_ck { get; set; }
        public decimal gia_ck { get; set; }
        public decimal gia_ck_nt { get; set; }
        public decimal ck { get; set; }
        public decimal ck_nt { get; set; }
        public decimal sl_dh { get; set; }
        public decimal sl_xuat { get; set; }
        public decimal sl_giao { get; set; }
        public string stt_rec_dh { get; set; }
        public string stt_rec0dh { get; set; }
        public string dh_so { get; set; }
        public decimal dh_ln { get; set; }
        public string stt_rec_px { get; set; }
        public string stt_rec0px { get; set; }
        public string px_so { get; set; }
        public decimal px_ln { get; set; }
        public string stt_rec_gh { get; set; }
        public string stt_rec0gh { get; set; }
        public string stt_rec_pn { get; set; }
        public string stt_rec0pn { get; set; }
        public string tk_gv { get; set; }
        public string tk_dt { get; set; }
        public string tk_ck { get; set; }
        public string tk_cpbh { get; set; }
        public bool px_gia_dd { get; set; }
        public string ma_nvbh_i { get; set; }
        public string ma_hd { get; set; }
        public string ma_ku { get; set; }
        public string ma_phi { get; set; }
        public string so_dh_i { get; set; }
        public string ma_td1 { get; set; }
        public string ma_td2 { get; set; }
        public string ma_td3 { get; set; }
        public string ma_thue { get; set; }
        public string tk_thue_no { get; set; }
        public string tk_thue_co { get; set; }
        public decimal thue_suat { get; set; }
        public string ma_imei { get; set; }
        public decimal gia_tra_lai { get; set; }

        public decimal tien_giam { get; set; }
        public decimal ty_le_giam { get; set; }
    }
}
