using Genbyte.Component.Voucher;

namespace Voucher.SVTran_BHK
{
    public class HtcDetail : DetailEntity
    {
        public string ma_vt { get; set; }
        public string ten_vt { get; set; }
        public string ma_sp { get; set; }
        public string ma_bp { get; set; }
        public string so_lsx { get; set; }
        public string dvt { get; set; }
        public decimal he_so { get; set; }
        public string ma_kho { get; set; }
        public string ma_vi_tri { get; set; }
        public string ma_lo { get; set; }
        public string ma_vv { get; set; }
        public string tk_vt { get; set; }
        public decimal so_luong { get; set; }
        public decimal gia_nt { get; set; }
        public decimal gia { get; set; }
        public decimal gia_nt0 { get; set; }
        public decimal gia0 { get; set; }
        public decimal tien_nt { get; set; }
        public decimal tien { get; set; }
        public string ma_thue { get; set; }
        public string tk_thue { get; set; }
        public decimal thue_suat { get; set; }
        public decimal thue { get; set; }
        public decimal thue_nt { get; set; }
        public decimal tt { get; set; }
        public decimal tt_nt { get; set; }
        public string xstatus { get; set; }
        public string xaction { get; set; }
        public decimal tien0 { get; set; }
        public decimal tien_nt0 { get; set; }
        public string ma_thue_nk { get; set; }
        public decimal thue_suat_nk { get; set; }
        public string tk_thue_nk { get; set; }
        public decimal nk { get; set; }
        public decimal nk_nt { get; set; }
        public string ma_thue_ttdb { get; set; }
        public decimal thue_suat_ttdb { get; set; }
        public string tk_thue_ttdb { get; set; }
        public decimal ttdb { get; set; }
        public decimal ttdb_nt { get; set; }
        public decimal cp_bh { get; set; }
        public decimal cp_bh_nt { get; set; }
        public decimal cp_vc { get; set; }
        public decimal cp_vc_nt { get; set; }
        public decimal cp_khac { get; set; }
        public decimal cp_khac_nt { get; set; }
        public decimal cp { get; set; }
        public decimal cp_nt { get; set; }
        public string stt_rec_ct { get; set; }
        public string stt_rec0ct { get; set; }
        public string ct_so { get; set; }
        public decimal ct_ln { get; set; }
        public string stt_rec_dh { get; set; }
        public string stt_rec0dh { get; set; }
        public string dh_so { get; set; }
        public decimal dh_ln { get; set; }
        public string stt_rec_pn { get; set; }
        public string stt_rec0pn { get; set; }
        public string pn_so { get; set; }
        public decimal pn_ln { get; set; }
        public decimal tien_hang { get; set; }
        public decimal tien_hang_nt { get; set; }
        public decimal line_nbr { get; set; }
        public string ma_hd { get; set; }
        public string ma_ku { get; set; }
        public string ma_phi { get; set; }
        public string so_dh_i { get; set; }
        public decimal gia_ck_nt { get; set; }
        public decimal gia_ck { get; set; }
        public decimal tien_ck_nt { get; set; }
        public decimal tien_ck { get; set; }
        public decimal tl_ck { get; set; }
        public decimal ck_nt { get; set; }
        public decimal ck { get; set; }
        public string ma_td1 { get; set; }
        public string ma_td2 { get; set; }
        public string ma_td3 { get; set; }
        public decimal sl_td1 { get; set; }
        public decimal sl_td2 { get; set; }
        public decimal sl_td3 { get; set; }
        public DateTime? ngay_td1 { get; set; }
        public DateTime? ngay_td2 { get; set; }
        public DateTime? ngay_td3 { get; set; }
        public string gc_td1 { get; set; }
        public string gc_td2 { get; set; }
        public string gc_td3 { get; set; }
        public string s1 { get; set; }
        public decimal s4 { get; set; }
        public decimal s5 { get; set; }
        public decimal s6 { get; set; }
        public DateTime? s7 { get; set; }
        public DateTime? s8 { get; set; }
        public DateTime? s9 { get; set; }
        public string ma_imei { get; set; }
        public string ma_loai { get; set; }
        public bool new_imei_yn { get; set; }
    }
}
